saia-i/ec-202210c

src/main/java/com/example/controller/InsertUserController.java
src/main/java/com/example/form/InsertUserForm.java
src/main/java/com/example/repository/UserRepository.java
src/main/java/com/example/service/InsertUserService.java
src/main/resources/templates/register_user.html

ユーザー登録と、登録時に不備があった場合はエラーが出るようにヴァリデーションをつけました。
ご確認よろしくお願い致します。
不備がありましたら教えていただけると幸いです。

1-1.ユーザを登録をする処理を行いました。

---

src/main/resources/static/js/item_detail.js
src/main/resources/templates/item_detail.html

合計金額自動反映機能を追加しました.

---

src/main/resources/templates/item_list.html

2-4商品名オートコンプリート機能を実装しました.

---

src/main/resources/templates/register_user.html

2-7住所検索機能を追加しました.

---

src/main/java/com/example/service/OrderService.java
src/main/resources/templates/cart_list.html
src/main/resources/templates/item_detail.html
src/main/resources/templates/item_list.html
src/main/resources/templates/order_confirm.html
src/main/resources/templates/order_finished.html
src/main/resources/templates/register_admin.html
src/main/resources/templates/register_user.html

正しく画面遷移するようにボタンにリンクをつけました（半分くらい）

---

pom.xml
src/main/java/com/example/common/GlobalExceptionHandler.java
src/main/java/com/example/common/SecurityConfig.java
src/main/java/com/example/common/package-info.java
src/main/java/com/example/service/OrderService.java
src/main/resources/templates/error/404.html
src/main/resources/templates/error/500.html

404,500エラーの際の遷移先のページを作りました。

---

src/main/java/com/example/controller/LoginUserController.java
src/main/java/com/example/form/LoginUserForm.java
src/main/java/com/example/repository/UserRepository.java
src/main/java/com/example/service/LoginUserService.java
src/main/resources/templates/login.html

1-2.ログイン/ログアウトをするのログイン機能だけ他機能追加で必要なようなので先にプッシュします！
別コントローラーと統合しないとエラーが起きる箇所があるため、その部分はコメントアウトにしました。
ご確認よろしくお願い致します。

1-2.ログインする(初級) 

---

src/main/java/com/example/controller/CartController.java
src/main/java/com/example/controller/OrderController.java
src/main/java/com/example/domain/Order.java
src/main/java/com/example/domain/OrderItem.java
src/main/java/com/example/repository/OrderRepository.java
src/main/java/com/example/service/OrderService.java
src/main/resources/templates/cart_list.html
src/main/resources/templates/item_detail.html
src/main/resources/templates/order_confirm.html

カートの中身を表示する機能を修正しました.

---

src/main/java/com/example/controller/LoginUserController.java
src/main/java/com/example/controller/LogoutUserController.java
src/main/resources/templates/cart_list.html
src/main/resources/templates/error/404.html
src/main/resources/templates/error/500.html
src/main/resources/templates/item_detail.html
src/main/resources/templates/item_list.html
src/main/resources/templates/login.html
src/main/resources/templates/order_confirm.html
src/main/resources/templates/order_finished.html
src/main/resources/templates/register_admin.html
src/main/resources/templates/register_user.html
src/main/resources/templates/top.html

下記作業を行いました。ご確認よろしくお願い致します。
・ログアウト機能の作成
・各HTMLのヘッダ（会員登録）とログイン・ログアウトのリンクを編集
不備当ございましたらコメントお願い致します。

1-2.ログアウトをする(初級) 

---

src/main/java/com/example/controller/OrderController.java
src/main/java/com/example/form/OrderForm.java
src/main/resources/templates/order_confirm.html

入力値チェックの機能を追加しました

---

src/main/resources/templates/item_list.html

商品一覧のページで画像にリンクを埋め込みました

---

src/main/resources/templates/cart_list.html
src/main/resources/templates/item_list.html
src/main/resources/templates/order_confirm.html

kaneko order_confirm.html 削除ボタンパス、金額修正

---

src/main/java/com/example/controller/OrderController.java
src/main/java/com/example/repository/OrderRepository.java
src/main/resources/templates/cart_list.html

バグの修正をしました

---

src/main/java/com/example/controller/LoginUserController.java
src/main/java/com/example/controller/ShowItemListController.java
src/main/resources/templates/cart_list.html
src/main/resources/templates/error/404.html
src/main/resources/templates/error/500.html
src/main/resources/templates/item_detail.html
src/main/resources/templates/item_list.html
src/main/resources/templates/login.html
src/main/resources/templates/order_confirm.html
src/main/resources/templates/order_finished.html
src/main/resources/templates/register_admin.html
src/main/resources/templates/register_user.html
src/main/resources/templates/top.html

bugfix3 商品画面へのパスを簡易化しました

---

src/main/java/com/example/service/OrderService.java
src/main/resources/static/js/item_detail.js
src/main/resources/templates/item_detail.html

商品詳細画面の数量のデフォルト表示を1にしました

---

src/main/java/com/example/service/CartService.java
src/main/resources/templates/cart_list.html
src/main/resources/templates/order_confirm.html

bugfix-6金額がカンマ区切りになるように修正しました.

---

src/main/resources/templates/cart_list.html
src/main/resources/templates/item_detail.html
src/main/resources/templates/order_confirm.html

「○○さんこんにちは」を、商品詳細画面、カート画面、注文確認画面に表示するよう改修しました。

追加機能 feature/showname

---

src/main/java/com/example/controller/OrderController.java
src/main/java/com/example/form/OrderForm.java
src/main/java/com/example/service/OrderService.java
src/main/resources/templates/order_confirm.html

bugfix-9 配達時間が3時間後以前の場合にエラーが出るよう修正しました

---

src/main/resources/static/js/item_detail.js

金額がカンマ区切りされるように修正しました.

---

src/main/java/com/example/controller/OrderHistoryController.java
src/main/java/com/example/controller/ShowDetailController.java
src/main/java/com/example/repository/OrderRepository.java
src/main/java/com/example/service/OrderHistoryService.java
src/main/resources/templates/cart_list.html
src/main/resources/templates/item_detail.html
src/main/resources/templates/item_list.html
src/main/resources/templates/order_confirm.html
src/main/resources/templates/order_finished.html
src/main/resources/templates/order_history.html

注文履歴を作成しました

---

src/main/resources/static/js/allchack_button.js
src/main/resources/templates/item_detail.html

トッピングの全件追加と全件解除のボタンを作成しました
